import { StyleSheet } from 'react-native';
import { colors } from '../../../../shared/theme/colors';
import { spacing, typography, shadows } from '../../../../shared/theme';

export const mapScreenWebStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  safeArea: { flex: 1, paddingHorizontal: spacing.md, paddingBottom: spacing.xl },
  searchBarContainer: { paddingVertical: spacing.sm, paddingHorizontal: spacing.xs, marginBottom: spacing.sm },
  mapCard: {
    flex: 2,
    minHeight: 280,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: colors.primaryDark,
    ...shadows.lg,
  },
  userInfoChip: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.95)',
    ...shadows.sm,
  },
  userInfoText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 12,
    color: colors.text,
  },
  createRequestButton: {
    position: 'absolute',
    left: spacing.md,
    bottom: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 9999,
    backgroundColor: colors.primary,
    gap: spacing.xs,
    ...shadows.md,
  },
  createRequestButtonText: { color: colors.primaryContrast },
  locationButton: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.lg,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    pointerEvents: 'none',
  },
  loadingOverlayContent: { alignItems: 'center', gap: spacing.sm },
  loadingOverlayText: { marginTop: spacing.xs },
  fallbackBanner: {
    position: 'absolute',
    top: spacing.sm,
    left: spacing.md,
    right: spacing.md,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 8,
    alignSelf: 'center',
  },
  fallbackBannerText: { color: '#fff', textAlign: 'center', fontFamily: typography.fontFamily.regular, fontSize: 12 },
  sheet: {
    flex: 1,
    minHeight: 200,
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -spacing.lg,
    ...shadows.lg,
  },
  legendWrap: {
    position: 'absolute',
    bottom: spacing.lg,
    left: spacing.md,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    ...shadows.sm,
  },
});
