import { StyleSheet } from 'react-native';
import { colors } from '../../../../shared/theme/colors';
import { spacing, typography, shadows, radii } from '../../../../shared/theme';

export const mapScreenWebStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  safeArea: { flex: 1, paddingHorizontal: spacing.md, paddingBottom: spacing.xl },
  searchBarContainer: { paddingVertical: spacing.sm, paddingHorizontal: spacing.xs, marginBottom: spacing.sm, zIndex: 25, position: 'relative' as const },
  mapCard: {
    flex: 1,
    minHeight: 280,
    borderRadius: 16,
    overflow: 'hidden' as const,
    backgroundColor: colors.primaryDark,
    ...shadows.lg,
  },
  mapHeader: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flex: 1,
    paddingRight: spacing.sm,
  },
  userInfoChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignSelf: 'flex-start',
    ...shadows.sm,
  },
  userInfoText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 12,
    color: colors.text,
  },
  fallbackBanner: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: spacing.sm,
  },
  fallbackBannerText: { color: '#fff', textAlign: 'center', fontFamily: typography.fontFamily.regular, fontSize: 12 },
  filterButton: {
    minWidth: 92,
    height: 44,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    ...shadows.sm,
  },
  mapArea: {
    flex: 1,
    position: 'relative',
  },
  legendWrap: {
    position: 'absolute',
    bottom: spacing.lg,
    left: spacing.md,
    zIndex: 5,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    ...shadows.sm,
  },
  mapInteractionBlocker: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.02)',
  },
  // Desktop dropdown panel.
  filterPanel: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.md,
    width: 240,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 20,
    ...shadows.lg,
    paddingVertical: spacing.xs,
  },
  filterPanelTitle: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontFamily: typography.fontFamily.semibold,
    fontSize: 13,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  filterRowText: {
    fontFamily: typography.fontFamily.medium,
    fontSize: 13,
    color: colors.text,
  },
  filterRowCheck: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary + '20',
  },
  // Mobile full-screen modal overlay for filters.
  filterOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.28)',
    zIndex: 22,
  },
  filterMobileSheet: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
    borderRadius: 24,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    ...shadows.lg,
    maxHeight: '70%',
  },
  filterMobileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  filterMobileCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...shadows.sm,
  },
  createRequestButton: {
    position: 'absolute',
    left: spacing.md,
    bottom: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 9999,
    backgroundColor: colors.primary,
    gap: spacing.xs,
    ...shadows.md,
    zIndex: 15,
  },
  createRequestButtonText: { color: colors.primaryContrast },
  locationButton: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.lg,
    zIndex: 14,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    pointerEvents: 'none',
    zIndex: 50,
  },
  loadingOverlayContent: { alignItems: 'center', gap: spacing.sm },
  loadingOverlayText: { marginTop: spacing.xs },
});
